### ISSUE TITLE
Add a setAll method to allow for a dynamic number of headers

### ISSUE THREAD

**Issue by nennes** [trooba/trooba#25]
### Description
When extracting the pipeline into a reusable package, different consumers may need to set a different amount of headers. We can achieve this via a local method that iterates on the headers and calls `set` for every one but this forces us to pass a variable around and mutate it. A more elegant solution would be to implement a `setAll` function inside the `PipePoint` prototype which would call `set` for every header. Please advise if there is a better solution for setting a variable amount of headers.

### Context
It allows for better readability and avoids passing objects around and mutating them.

### Possible Implementation
Something like:
```
  setAll: function (data) {
    Object.entries(data).forEach(([name, value]) => this.set(name, value))
    return this;
  }
```

### Is this something you're interested in working on?
Yes

**Comment by dimichgh** [comment]
This is not for the headers. 
This is for context and if you need to set may of the at once, you can use

pipe.create({
    foo: 'bar',
    qaz: 'wsx'
    ...
});

You can also define you own API with may have setAll like https://github.com/trooba/trooba-http-transport/blob/master/index.js#L79

**Comment by dimichgh** [comment]
@nennes

**Comment by nennes** [comment]
Thanks for the suggestions @dimichgh, the `create` method solves my issue! 🙇
